### ISSUE TITLE
Problemi con i metadata per Facebook e Twitter

### ISSUE THREAD

**Issue by mtrimarchi** [dottorblaster/dottorblaster.github.io#2]
Provando ad usare i validatori di [Facebook](https://developers.facebook.com/tools/debug) e [Twitter](https://cards-dev.twitter.com/validator) sembra che alcune delle proprietà richieste dai due social network non siano presenti.

# Facebook
Per quanto concerne Facebook vengono riportati questi due problemi:

- **Inferred Property** The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

- **Share App ID Missing** The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.

Da documentazione i valori che devono essere presenti sono i seguenti:
```
<meta property="fb:app_id"          content="xxx" />
<meta property="og:type"            content="xxx" />
<meta property="og:url"             content="xxx" />
<meta property="og:title"           content="xxx" />
<meta property="og:image"           content="xxx" />
<meta property="og:description"     content="xxx" />
```

Fonte: [https://developers.facebook.com/docs/sharing/opengraph/using-objects](https://developers.facebook.com/docs/sharing/opengraph/using-objects)

# Twitter
Purtroppo l'utility per fare troubleshooting su Twitter Card non è completa come quella presente su Facebook e dunque non permette lo scrape in realtime con tanto di debug dei metadata.

Da documentazione i valori che devono essere presenti sono i seguenti:
```
<meta name="twitter:card"           content="xxx" />
<meta name="twitter:url"            content="xxx" />
<meta name="twitter:title"          content="xxx" />
<meta name="twitter:image:src"      content="xxx" />
<meta name="twitter:description"    content="xxx" />
<meta name="twitter:site"           content="xxx" />
<meta name="twitter:domain"         content="xxx" />
<meta name="twitter:creator"        content="xxx" />
```
Fonte: [https://dev.twitter.com/cards/types/summary](https://dev.twitter.com/cards/types/summary)

**Comment by dottorblaster** [comment]
Chiudo perché da https://github.com/dottorblaster/dottorblaster.github.io/commit/81602491e8e2e3a400eec76650400ca5f7c92dba la situazione è migliorata molto. og:image non posso fornirla in modo esplicito, fb:app_id potrei ma per ora il debug funziona da paura 😆 

Stesso dicasi per Twitter.
